### ISSUE TITLE
What is the result of image conversion of your anime-style-transfer?Do you have any test examples？

### ISSUE THREAD

**Issue by longxiong2016** [racinmat/anime-style-transfer#1]

**Comment by racinmat** [comment]
Sorry, I did not have time to do stuff in this project, but I have some time now. 
So I added some results to the readme, see for yourself. Those are from training dataset, but some test images will come soon.

**Comment by racinmat** [comment]
I added some results on testing data (not used for training), thus I am closing this issue. Sorry it took so long.
